name: Test React App
on: push
jobs:
    test_my_app:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Test aplication
              run: npm run test

    build_my_app:
      runs-on: ubuntu-latest
      steps:
          - name: Get repository code
            uses: actions/checkout@v3
          - name: Install dependencies
            run: npm ci
          - name: Build aplication
            run: npm run build
          - name: Deploy
            run: echo deploying...